name: dice_app
description: Dice Application.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/dice1.png
    - assets/images/dice2.png
    - assets/images/dice3.png
    - assets/images/dice4.png
    - assets/images/dice5.png
    - assets/images/dice6.png